- name: Common Roles
  hosts: localhost
  roles:
    - common
  tags:
    - common-role

- name: Certbot
  hosts: localhost
  roles:
    - certbot
  tags:
    - certbot-role

- name: Mail Roles
  hosts: localhost
  roles:
    - mail
  tags:
    - mail-role


  # vars_prompt:
  #   - name: aws_access_key_id
  #     prompt: AWS Access Key ID
  #     private: false

  #   - name: aws_secret_access_key
  #     prompt: AWS Secret Access Key
  #     private: true

  #   - name: aws_session_token
  #     prompt: AWS Session Token
  #     private: true

  #   - name: acme_email
  #     prompt: ACME email address
  #     private: false
