---
email_domain: example.com
email_host: examplehost
# TLS
mail_dovecot_min_tls: 1.2

# Cleartext Considered Obsolete: Use of Transport Layer Security (TLS)
# for Email Submission and Access
# https://datatracker.ietf.org/doc/html/rfc8314
mail_dovecot_disable_plaintext: true

# TLS Certs
mail_dovecot_tls_cert:
mail_dovecot_tls_key:
mail_dovecot_tls_letsencrypt: false

# TLS 1.2
# TLS configuration from the Mozilla SSL Configuration Guide
# https://ssl-config.mozilla.org/#server=dovecot&version=2.3.21&config=modern&openssl=3.0.13&guideline=5.7
#
# generated 2025-02-16, Mozilla Guideline v5.7, Dovecot 2.3.21, OpenSSL 3.0.13, modern config
#
mail_dovecot_tls_diffie_hellman: true
mail_dovecot_tls_cipher_list: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305

# TLS 1.3
# TLS configuration from the Mozilla SSL Configuration Guide
# https://ssl-config.mozilla.org/#server=dovecot&version=2.3.21&config=intermediate&openssl=3.0.13&guideline=5.7
#
# generated 2024-07-08, Mozilla Guideline v5.7, Dovecot 2.3.21, OpenSSL 3.0.13, intermediate configuration
mail_dovecot_tls_curve_list: X25519:prime256v1:secp384r1

# Dovecot Features
mail_dovecot_sieve: true
mail_dovecot_compression: true
