- name: Create Mail Directories
  become: true
  loop:
    - /var/mail/virtual
    - /var/mail/virtual/conf.d/
  ansible.builtin.file:
    path: "{{ item }}"
    mode: u=rwx,g=rwx,o=rx
    owner: root # TODO
    group: root # TODO
    state: directory

- name: Create Domain Mail Directories
  become: true
  loop:
    - /var/mail/virtual/conf.d/{{ mail_email_domain }}
    - /var/mail/virtual/{{ mail_email_domain }}
  ansible.builtin.file:
    path: "{{ item }}"
    mode: u=rwx,g=rwx,o=trwx
    owner: root # TODO
    group: root # TODO
    state: directory

- name: Dovecot disable default system auth
  become: true
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    search_string: "!include auth-system.conf.ext"
    line: "#!include auth-system.conf.ext"
  notify: "mail : Restart Dovecot"

- name: Copy Dovecot local.conf
  become: true
  ansible.builtin.template:
    src: dovecot/local.conf.j2
    dest: /etc/dovecot/local.conf
    mode: u=rw,g=r,o=
    owner: root
    group: dovecot
  notify: "mail : Restart Dovecot"

- name: Copy Dovecot Users
  become: true
  ansible.builtin.copy:
    src: dovecot/users
    dest: /etc/dovecot/users
    mode: u=rw,g=r,o=
    owner: root
    group: dovecot
    force: false
  notify: "mail : Restart Dovecot"

# Consider making local.d and including from local.conf
