- name: FirewallD Postfix SMTP
  become: true
  ansible.posix.firewalld:
    service: smtp
    zone: public
    state: enabled
    immediate: true
    permanent: true
- name: FirewallD Postfix SMTPs
  become: true
  ansible.posix.firewalld:
    service: smtps
    zone: public
    state: enabled
    immediate: true
    permanent: true

- name: FirewallD IMAPs
  become: true
  ansible.posix.firewalld:
    service: imaps
    zone: public
    state: enabled
    immediate: true
    permanent: true
- name: FirewallD managesieve
  become: true
  ansible.posix.firewalld:
    service: managesieve
    zone: public
    state: enabled
    immediate: true
    permanent: true
