- name: Install Packages
  ansible.builtin.import_tasks: apt.yaml

- name: Get certificate
  ansible.builtin.import_role:
    name: acme
  vars:
    acme_hostname: "{{ mail_email_hostname }}"
    acme_dns_zone: "{{ mail_email_domain }}"
    # - role: acme
    #   # aws_access_key_id: "{{ aws_access_key_id }}"
    #   # aws_secret_access_key: "{{ aws_secret_access_key }}"
    #   # aws_session_token: "{{ aws_session_token }}"
    #   # acme_email: "{{ acme_email }}"

- name: RSpamd
  ansible.builtin.import_tasks: rspamd.yaml

- name: Debug
  ansible.builtin.debug:
    var: vars

- name: Dovecot
  ansible.builtin.import_tasks: dovecot.yaml

- name: Postfix
  ansible.builtin.import_tasks: postfix.yaml

- name: Update FirewallD
  ansible.builtin.import_tasks: firewalld.yaml
