- name: Install Packages
  ansible.builtin.import_tasks: apt.yaml

- name: RSpamd
  ansible.builtin.import_tasks: rspamd.yaml

- name: Dovecot
  ansible.builtin.import_tasks: dovecot.yaml

- name: Postfix
  ansible.builtin.import_tasks: postfix.yaml

- name: Update FirewallD
  ansible.builtin.import_tasks: firewalld.yaml
