# - name: Include
#   loop:
#     - apt.yaml
#     - systemd-user.yaml
#     - shell.yaml
#   ansible.builtin.include_tasks:
#     file: "{{ item }}"

- name: Core Apt Updates
  ansible.builtin.import_tasks: apt.yaml

- name: Install Fish
  ansible.builtin.import_tasks: shell.yaml

- name: SystemD
  ansible.builtin.import_tasks: systemd-user.yaml

- name: FirewallD
  ansible.builtin.import_tasks: firewalld.yaml

- name: SSH Guard
  ansible.builtin.import_tasks: sshguard.yaml

- name: Tmux
  ansible.builtin.import_tasks: tmux.yaml
